/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewPlayer;

import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import Tools.DropDown;
import static Tools.getConnection.getConnection;
import static Tools.setValuesComboBox.setValuesComboBox;

/**
 *
 * @author Viko
 */
public class NewPlayer extends javax.swing.JFrame {

    String ImgPath = null;
    int pos = 0;

    /**
     * Creates new form TableTennis
     */
    public NewPlayer() {
        initComponents();
        setValuesComboBox("select C.ID, C.CITY from CITIES C", jcbCity, true, -1, false);
        setValuesComboBox("select G.ID, G.GENDER from GENDERS G", jcbGender, false, -1, false);
        String sql = "select T.ID, T.TEAM from TEAMS T \n"
                + "where\n"
                + "(select count(0) from PLAYERS P where P.TEAM_REF = T.ID) < 2";
        setValuesComboBox(sql, jcbTeam, true, -1, false);
    }

    public boolean checkInputs() {
        if (jtxtFirstName.getText() == null
                || jtxtLastName.getText() == null
                || jcbCity.getSelectedIndex() == -1
                || jcbTeam.getSelectedIndex() == -1
                || jcbGender.getSelectedIndex() == -1
                || jdateBirthday.getDate() == null
                || jtxtMobilePhone.getText() == null
                || jtxtAddress.getText() == null) {
            return false;
        }
        return true;
    }

    public ImageIcon ResizeImage(String ImagePath, byte[] pic) {
        ImageIcon myImage = null;
        if (ImagePath != null) {
            myImage = new ImageIcon(ImagePath);
        } else {
            myImage = new ImageIcon(pic);
        }

        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(jPhoto.getWidth(), jPhoto.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLastName = new javax.swing.JLabel();
        jTeam = new javax.swing.JLabel();
        jFirstName = new javax.swing.JLabel();
        jGender = new javax.swing.JLabel();
        jCity = new javax.swing.JLabel();
        jtxtLastName = new javax.swing.JTextField();
        jtxtFirstName = new javax.swing.JTextField();
        jcbTeam = new javax.swing.JComboBox<>();
        jcbCity = new javax.swing.JComboBox<>();
        jcbGender = new javax.swing.JComboBox<>();
        jPhoto = new javax.swing.JLabel();
        jbtnChoose = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jtxtMobilePhone = new javax.swing.JTextField();
        jBirthdayDate = new javax.swing.JLabel();
        jMobilePhone1 = new javax.swing.JLabel();
        jdateBirthday = new com.toedter.calendar.JDateChooser();
        jAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAddress = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setTitle("New Player");
        setBackground(new java.awt.Color(255, 255, 51));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("NEW PLAYER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 100));

        jLastName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLastName.setForeground(new java.awt.Color(255, 255, 255));
        jLastName.setText("Last Name:");
        getContentPane().add(jLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 160, 40));

        jTeam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTeam.setForeground(new java.awt.Color(255, 255, 255));
        jTeam.setText("Team:");
        getContentPane().add(jTeam, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 160, 40));

        jFirstName.setBackground(new java.awt.Color(255, 255, 255));
        jFirstName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jFirstName.setForeground(new java.awt.Color(255, 255, 255));
        jFirstName.setText("First Name:");
        getContentPane().add(jFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 160, 40));

        jGender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jGender.setForeground(new java.awt.Color(255, 255, 255));
        jGender.setText("Gender:");
        getContentPane().add(jGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 160, 40));

        jCity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCity.setForeground(new java.awt.Color(255, 255, 255));
        jCity.setText("City:");
        getContentPane().add(jCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 160, 40));
        getContentPane().add(jtxtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 220, 30));
        getContentPane().add(jtxtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 220, 30));

        jcbTeam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbTeam.setSelectedIndex(-1);
        getContentPane().add(jcbTeam, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 220, 30));

        jcbCity.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jcbCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 220, 30));

        jcbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbGender.setSelectedIndex(-1);
        getContentPane().add(jcbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 220, 30));

        jPhoto.setBackground(new java.awt.Color(0, 0, 153));
        jPhoto.setOpaque(true);
        getContentPane().add(jPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 170, 140));

        jbtnChoose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewPlayer/Choose Photo.png"))); // NOI18N
        jbtnChoose.setText("Choose Photo");
        jbtnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChooseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 170, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewPlayer/Insert.png"))); // NOI18N
        jButton2.setText("Insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 600, 100, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewPlayer/back.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 100, -1));
        getContentPane().add(jtxtMobilePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 220, 30));

        jBirthdayDate.setBackground(new java.awt.Color(255, 255, 255));
        jBirthdayDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBirthdayDate.setForeground(new java.awt.Color(255, 255, 255));
        jBirthdayDate.setText("Birthday Date:");
        getContentPane().add(jBirthdayDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 160, 40));

        jMobilePhone1.setBackground(new java.awt.Color(255, 255, 255));
        jMobilePhone1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMobilePhone1.setForeground(new java.awt.Color(255, 255, 255));
        jMobilePhone1.setText("Mobile Phone:");
        getContentPane().add(jMobilePhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 160, 40));
        getContentPane().add(jdateBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 220, 30));

        jAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jAddress.setForeground(new java.awt.Color(255, 255, 255));
        jAddress.setText("Address:");
        getContentPane().add(jAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 160, 40));

        jtxtAddress.setColumns(20);
        jtxtAddress.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jtxtAddress.setRows(5);
        jScrollPane1.setViewportView(jtxtAddress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 220, 90));

        jPanel2.setBackground(new java.awt.Color(51, 0, 204));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 80));

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 890, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChooseActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));

        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            jPhoto.setIcon(ResizeImage(path, null));
            ImgPath = path;
        } else {
            System.out.println("No File selected");
        }

    }//GEN-LAST:event_jbtnChooseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (checkInputs() && ImgPath != null) {
            try {
                Connection con = getConnection();
                PreparedStatement ps = con.prepareStatement("insert into PLAYERS (FIRSTNAME, LASTNAME, CITY_REF, GENDER_REF, BIRTHDAY_DATE, TEAM_REF, PICTURE, CATEGORY_REF, ADDRESS, PHONE)"
                        + "values (?,?,?,?,?,?,?,?,?,?)");

                ps.setString(1, jtxtFirstName.getText());
                ps.setString(2, jtxtLastName.getText());
                ps.setInt(3, ((DropDown) jcbCity.getSelectedItem()).getId());
                ps.setInt(4, ((DropDown) jcbGender.getSelectedItem()).getId());
                java.sql.Date sqldate = new java.sql.Date(jdateBirthday.getDate().getTime());
                ps.setDate(5, sqldate);
                ps.setInt(6, ((DropDown) jcbTeam.getSelectedItem()).getId());
                InputStream img = new FileInputStream(new File(ImgPath));
                ps.setBlob(7, img);
                ps.setInt(8, ((DropDown) jcbGender.getSelectedItem()).getId());
                ps.setString(9, jtxtAddress.getText());
                ps.setString(10, jtxtMobilePhone.getText());

                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Inserted!");
            } catch (HeadlessException | FileNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "One or more fields are empty!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewPlayer().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAddress;
    private javax.swing.JLabel jBirthdayDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jCity;
    private javax.swing.JLabel jFirstName;
    private javax.swing.JLabel jGender;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLastName;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JLabel jMobilePhone1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jPhoto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTeam;
    private javax.swing.JButton jbtnChoose;
    private javax.swing.JComboBox<String> jcbCity;
    private javax.swing.JComboBox<String> jcbGender;
    public javax.swing.JComboBox<String> jcbTeam;
    private com.toedter.calendar.JDateChooser jdateBirthday;
    private javax.swing.JTextArea jtxtAddress;
    private javax.swing.JTextField jtxtFirstName;
    private javax.swing.JTextField jtxtLastName;
    private javax.swing.JTextField jtxtMobilePhone;
    // End of variables declaration//GEN-END:variables
}
