package EditTeam;

import static Tools.getConnection.getConnection;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Viko
 */
public class Edit extends javax.swing.JFrame {

    /**
     * Creates new form MainWindows
     */
    public Edit() {
        initComponents();
        Show_Teams_In_JTable();

    }
    String ImgPath = null;
    int pos = 0;

    public ImageIcon ResizeImage(String ImagePath, byte[] pic) {
        ImageIcon myImage = null;
        if (ImagePath != null) {
            myImage = new ImageIcon(ImagePath);
        } else {
            myImage = new ImageIcon(pic);
        }

        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(jChoosedPicture.getWidth(), jChoosedPicture.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }

    private ArrayList<EditTeam> getTeamsList() {
        ArrayList<EditTeam> teamList = new ArrayList<>();
        Connection con = getConnection();
        String query = "SELECT T.ID, T.TEAM,T.ESTABLISHMENT, C.CITY, T.ADDRESS, T.MOBILE_PHONE, T.PICTURE  FROM TEAMS T join CITIES C on C.ID = T.CITY_REF";

        Statement st;
        ResultSet rs;

        try {

            st = con.createStatement();
            rs = st.executeQuery(query);
            EditTeam Team;

            while (rs.next()) {
                Team = new EditTeam(rs.getInt("ID"), rs.getString("TEAM"), rs.getString("CITY"), rs.getString("ADDRESS"), rs.getString("MOBILE_PHONE"), rs.getDate("ESTABLISHMENT"), rs.getBytes("PICTURE"));
                teamList.add(Team);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        }

        return teamList;

    }

    private void Show_Teams_In_JTable() {
        ArrayList<EditTeam> list = getTeamsList();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        Object[] row = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getID();
            row[1] = list.get(i).getName();
            row[2] = list.get(i).getCity();
            row[3] = list.get(i).getAddress();
            row[4] = list.get(i).getDateEstablishment();
            row[5] = list.get(i).getMobilePhone();

            model.addRow(row);
        }

    }

    private void ShowItem(int index) {
        jtxtID.setText(Integer.toString(getTeamsList().get(index).getID()));
        jtxtName.setText(getTeamsList().get(index).getName());
        jtaAddress.setText(getTeamsList().get(index).getAddress());
        jtxtMobilePhone.setText(getTeamsList().get(index).getMobilePhone());
        jChoosedPicture.setIcon(ResizeImage(null, getTeamsList().get(index).getPicture()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jName = new javax.swing.JLabel();
        jChoosedPicture = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnChoosePicture = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnFirst = new javax.swing.JButton();
        jbtnNext = new javax.swing.JButton();
        jbtnPrevious = new javax.swing.JButton();
        jbtnLast = new javax.swing.JButton();
        jID = new javax.swing.JLabel();
        jtxtID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jName1 = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaAddress = new javax.swing.JTextArea();
        jMobilePhone1 = new javax.swing.JLabel();
        jtxtMobilePhone = new javax.swing.JTextField();

        setTitle("Edit Team");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jName.setForeground(new java.awt.Color(255, 255, 255));
        jName.setText("Address:");
        jName.setToolTipText("");
        jPanel1.add(jName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, 20));

        jChoosedPicture.setBackground(new java.awt.Color(0, 51, 204));
        jChoosedPicture.setOpaque(true);
        jPanel1.add(jChoosedPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 159, 117));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "City", "Address", "Date  Establishment", "Mobile Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 700, 341));

        jbtnChoosePicture.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnChoosePicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EditTeam/Choose Photo.png"))); // NOI18N
        jbtnChoosePicture.setText("CHOOSE PICTURE");
        jbtnChoosePicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChoosePictureActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnChoosePicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EditTeam/delete.png"))); // NOI18N
        jbtnDelete.setText("DELETE");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, -1, -1));

        jbtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EditTeam/update.png"))); // NOI18N
        jbtnUpdate.setText("UPDATE");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        jbtnFirst.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EditTeam/first.png"))); // NOI18N
        jbtnFirst.setText("FIRST");
        jbtnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFirstActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 107, -1));

        jbtnNext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EditTeam/next.png"))); // NOI18N
        jbtnNext.setText("NEXT");
        jbtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNextActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 107, -1));

        jbtnPrevious.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EditTeam/previous.png"))); // NOI18N
        jbtnPrevious.setText("PREVIOUS");
        jbtnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPreviousActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 520, -1, -1));

        jbtnLast.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EditTeam/last.png"))); // NOI18N
        jbtnLast.setText("LAST");
        jbtnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLastActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 520, 107, -1));

        jID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jID.setForeground(new java.awt.Color(255, 255, 255));
        jID.setText("ID:");
        jID.setToolTipText("");
        jPanel1.add(jID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jtxtID.setEditable(false);
        jtxtID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtxtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 52, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EditTeam/back.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 100, -1));

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("EDIT TEAM");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 340, 100));

        jName1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jName1.setForeground(new java.awt.Color(255, 255, 255));
        jName1.setText("Name:");
        jName1.setToolTipText("");
        jPanel1.add(jName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jtxtName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 190, 30));

        jtaAddress.setColumns(20);
        jtaAddress.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jtaAddress.setRows(5);
        jScrollPane2.setViewportView(jtaAddress);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 220, 90));

        jMobilePhone1.setBackground(new java.awt.Color(255, 255, 255));
        jMobilePhone1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMobilePhone1.setForeground(new java.awt.Color(255, 255, 255));
        jMobilePhone1.setText("Mobile Phone:");
        jPanel1.add(jMobilePhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 160, 20));
        jPanel1.add(jtxtMobilePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 220, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1199, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        String UpdateQuery = null;
        PreparedStatement ps = null;
        Connection con = getConnection();

        if (ImgPath == null) {
            try {
                UpdateQuery = "UPDATE TEAMS SET TEAM = ?, ADDRESS = ?, MOBILE_PHONE = ? WHERE ID = ?";
                ps = con.prepareStatement(UpdateQuery);

                ps.setString(1, jtxtName.getText());
                ps.setString(2, jtaAddress.getText());
                ps.setString(3, jtxtMobilePhone.getText());
                ps.setInt(4, Integer.parseInt(jtxtID.getText()));

                ps.executeUpdate();
                Show_Teams_In_JTable();
                JOptionPane.showMessageDialog(null, "Team Updated");

            } catch (SQLException ex) {
                Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
            }

        } // update With Image
        else {
            try {
                InputStream img = new FileInputStream(new File(ImgPath));

                UpdateQuery = "UPDATE TEAMS SET TEAM = ?, ADDRESS = ?, MOBILE_PHONE = ?, PICTURE = ? WHERE ID = ?";

                ps = con.prepareStatement(UpdateQuery);

                ps.setString(1, jtxtName.getText());
                ps.setString(2, jtaAddress.getText());
                ps.setString(3, jtxtMobilePhone.getText());

                ps.setBlob(4, img);

                ps.setInt(5, Integer.parseInt(jtxtID.getText()));

                ps.executeUpdate();
                Show_Teams_In_JTable();
                JOptionPane.showMessageDialog(null, "Team Updated");

            } catch (HeadlessException | FileNotFoundException | NumberFormatException | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnChoosePictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChoosePictureActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));

        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            jChoosedPicture.setIcon(ResizeImage(path, null));
            ImgPath = path;
            // }else{
            //  System.out.println("No File selected");
        }

    }//GEN-LAST:event_jbtnChoosePictureActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int index = jTable1.getSelectedRow();
        ShowItem(index);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbtnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFirstActionPerformed
        pos = 0;
        ShowItem(pos);
    }//GEN-LAST:event_jbtnFirstActionPerformed

    private void jbtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNextActionPerformed
        pos++;

        if (pos >= getTeamsList().size()) {
            pos = getTeamsList().size() - 1;
        }

        ShowItem(pos);
    }//GEN-LAST:event_jbtnNextActionPerformed

    private void jbtnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPreviousActionPerformed
        pos--;

        if (pos < 0) {
            pos = 0;
        }

        ShowItem(pos);
    }//GEN-LAST:event_jbtnPreviousActionPerformed

    private void jbtnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLastActionPerformed
        pos = getTeamsList().size() - 1;
        ShowItem(pos);
    }//GEN-LAST:event_jbtnLastActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        String UpdateQuery = null;
        PreparedStatement ps = null;
        Connection con = getConnection();
        try {
            UpdateQuery = "DELETE FROM TEAMS  WHERE ID = ?";
            ps = con.prepareStatement(UpdateQuery);

            ps.setInt(1, Integer.parseInt(jtxtID.getText()));

            ps.executeUpdate();
            Show_Teams_In_JTable();
            JOptionPane.showMessageDialog(null, "Team Deleted");

        } catch (SQLException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Edit().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jChoosedPicture;
    private javax.swing.JLabel jID;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jMobilePhone1;
    private javax.swing.JLabel jName;
    private javax.swing.JLabel jName1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnChoosePicture;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnFirst;
    private javax.swing.JButton jbtnLast;
    private javax.swing.JButton jbtnNext;
    private javax.swing.JButton jbtnPrevious;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTextArea jtaAddress;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextField jtxtMobilePhone;
    private javax.swing.JTextField jtxtName;
    // End of variables declaration//GEN-END:variables
}
